[phases.setup]
nixPkgs = ["python311", "nodejs_22"]

[phases.install]
cmds = [
  "python -m pip install -r requirements.txt",
  "npm install mineflayer"
]

[start]
cmd = "python app.py"

[variables]
  NIXPACKS_PYTHON_VERSION = "3.11"
  NODE_VERSION = "22"