[phases.setup]
nixPkgs = ["python311", "nodejs_22"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install mineflayer"
]

[start]
cmds = ["python app.py"]

[variables]
  NIXPACKS_PYTHON_VERSION = "3.11"
  NODE_VERSION = "22"